### ISSUE TITLE
Saving duplicated

### ISSUE THREAD

**Issue by ghost** [DenizShabani/SimpleTelegramScraper#1]
this script as duplicating name of users on members.csv file

example

user1,102993938484
user1,120932939393983

the id change but user nothing, and not filtering correctly the active users
tested on windows 10 machine

**Comment by DenizShabani** [comment]
Hey can you text me on telegram and replicate this issue. Would really appreciate it

**Comment by DenizShabani** [comment]
the active users are filtered based on users last seen recently. I will change it to the people who have been online in the last week soon.
